services:
  postgres:
    image: postgres:17.6-alpine
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydatabase
    restart: unless-stopped
